version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    restart: always
    networks:
      - deploy_network

  fastapi:
    build: backend/
    ports: 
      - 8000:8000
    container_name: fastapi
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    restart: always
    networks:
      - deploy_network

  streamlit-app:
    build: frontend/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    container_name: frontend
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge
